version: "3.4"
services:
  apache-web:
    stdin_open: true
    tty: true
    environment:
      - LANG=${LANG}
      - LC_ALL=${LC_ALL}
    build:
      context: .
      dockerfile: cent.Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    user: apache
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
