version: "3.4"
services:
  apache-test:
    stdin_open: true
    tty: true
    environment:
      - LANG=${LANG}
      - LC_ALL=${LC_ALL}
    #cpus: 0.5
    #cpu_shares: 5
    #cpuset: 0,1
    build:
      context: .
      dockerfile: apache.Dockerfile
    restart: unless-stopped
    # command: bash -c "
    #   useradd -m /home/${APACHE_ADMIN} -s /bin/bash ${APACHE_ADMIN} \
    #   cp ../index-apache.html:/var/www/html/index.html"
    ports:
      - "8080:8080"
    user: apache
    hostname: ${APACHE_SERVER_HOSTNAME}
    container_name: ${APACHE_SERVER_HOSTNAME}
    mac_address: ${APACHE_MAC_ADDRESS}
    networks:
      docker-frontend:
        ipv4_address: ${IP_APACHE}
        aliases:
          - ${APACHE_SERVER_HOSTNAME}
      # external: true     --> Uncomment if network exists

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ../index-apache.html:/var/www/html/index.html
      - ../apache/httpd:/etc/httpd
      - ../../portfolio-website-proj/apache:/etc/httpd/sites-available/portfolio-website-proj
      - /sys/fs/cgroup:/sys/fs/cgroup

networks:
  docker-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
