version: "3.6"
services:
  apache-test:
    build: ./apache.Dockerfile
    target: apache
    ports:
      - "8080:80"
    volumes:
      - index.html:/usr/local/apache2/htdocs
  networks:
    docker-frontend:
      name: custom_frontend
      driver: bridge
    # external: true     --> Uncomment if network exists
